### ISSUE TITLE
Volume flyout does not show apps after enabling spatial audio APO

### ISSUE THREAD

**Issue by LTHPKBTE** [File-New-Project/EarTrumpet#1049]
### Summary

After adjusting the spatial sound effect of the playback device, the volume mixer displays empty.

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/53574505/152020941-6d3c2d11-4524-47c9-90e7-ad9bf1b6c516.png)
![图片](https://user-images.githubusercontent.com/53574505/152020973-704dfec3-eeb6-4e72-aed8-e2537409abd2.png)
![图片](https://user-images.githubusercontent.com/53574505/152021310-2f56c479-8417-40fd-a909-8d10780aebe0.png)
![图片](https://user-images.githubusercontent.com/53574505/152021381-a37618d9-6151-4c60-9933-62fcea7250de.png)
all apps will disapper from the volume mixer(on one device)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.22000.469

### Additional information

Since I can't speak English, this article is translated into English by machine.

**Comment by riverar** [comment]
@LTHPKBTE Thanks, great report and English. I will investigate this.

**Comment by LemmusLemmus** [comment]
I have the same problem. Every single time I change the spatial audio I also have to restart EarTrumpet, since all applications started before the spatial audio change will be hidden in the EarTrumpet menu.

I often switch between spatial sound off and Dolby Atmos. Additionally, if I have Dolby Atmos enabled when I turn off my PC, Windows will, very annoyingly, boot with Windows Sonic enabled. As such this problem has become quite the annoyance.

It would be great if EarTrumpet could better support spatial audio. It might be worth implementing such support alongside #660 (and perhaps also #905). I'd also love if EarTrumpet could somehow prevent Windows 10 from changing my spatial audio to Windows Sonic, although that might be hoping for too much.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
