### ISSUE TITLE
EarTrumpet fails to switch iTunes to another device

### ISSUE THREAD

**Issue by DanteDT** [File-New-Project/EarTrumpet#1164]
### Summary

As 4th screenshot illustrates, this issue is only for iTunes. If headphones are plugged in *after* iTunes starts, EarTrumpet cannot switch audio to the new device (headphones) but seems to think that it has. Works fine for other players, ex. Firefox:
![et-fails-to-switch-itunes-01](https://user-images.githubusercontent.com/7212088/169708389-11c9f922-4a9f-4ccf-9f24-b5cc950dd38b.png)
![et-fails-to-switch-itunes-02](https://user-images.githubusercontent.com/7212088/169708399-da3eca29-cf49-4295-a8f4-ec90613ba75f.png)
![et-fails-to-switch-itunes-03](https://user-images.githubusercontent.com/7212088/169708402-18824335-28fe-4945-acd8-51c1a71d91a3.png)
![et-fails-to-switch-itunes-04](https://user-images.githubusercontent.com/7212088/169708406-52e699f9-a2d8-41b5-b253-95d5b08add17.png)

### Steps to reproduce

Start iTunes and another audio player like Firefox *without* headphones plugged in, so audio plays out system speakers.
Plug in headphones.
Use EarTrumpet as shown above to switch iTunes audio to headphones.
Use EarTrumpet as shown above to switch Firefox audio to headphones.

It works for Firefox, not for iTunes

### EarTrumpet version

2.2.0.0.

### Windows version

21H2 build 22000.675

**Comment by riverar** [comment]
Hey @DanteDT thanks for the report.

![image](https://user-images.githubusercontent.com/475132/169709072-9f898a94-1e36-42ba-963c-b65ede625446.png)

I added `windows-bug` as this is broken in Windows too. I also added `third-party-bug` as iTunes is frankly a bad app (likely purposeful) and doesn't appear to call audio APIs correctly.

Don't think you'll see a fix for this, I'm afraid. But two things:
* I strongly recommend you file an issue in Feedback Hub under `Devices and Drivers` > `Audio and sound`
* I will start an incompatible-app list and link in the README

**Comment by DanteDT** [comment]
>     * I will start an incompatible-app list and link in the README

Indeed, a bad app, and without a doubt purposeful! So turns the world with internecine tech subversions : )

I've reported the windows bug as you suggested - Feedback Hub.

**Comment by dobesv** [comment]
I've noticed that if an app has the ability to change the output device in its own settings, EarTrumpet might not be able to control that.  EarTrumpet only redirects apps that are trying to use the default output device.

**Comment by neube3** [comment]
> I've noticed that if an app has the ability to change the output device in its own settings, EarTrumpet might not be able to control that. EarTrumpet only redirects apps that are trying to use the default output device.

Thank you @dobesv, you ended my week-long quest for a fix!

For future reference for others:
MS Teams has two audio outputs and only one of them would truly switch in EarTrumpet (the general sounds; the actual calls would claim they've switched, but were under the wrong device anyway).

After a windows update, MS Teams decided it will silently (pun kind of intended) reset sound output settings.

I would then be able to switch one of MS Teams audio outputs to another device, _both outputs would **claim** to be switched/moved_, but the "call/conference" one (in an iron grip of MS Teams internal control) would stay right where it was. 

As you see on the fragment of a screenshot below (modified for unblurring the names of output devices), the second MS Teams output is in the headphones device's section (as it reverted to this setting in MS Teams itself without a notice), but after a right-click on it, it has a tick/check mark next to "CABLE Input (VB-Audio Virtual Cable)", suggesting it has switched. 

![image](https://user-images.githubusercontent.com/18572821/185882769-67ce4704-7600-41f9-905b-4a1f5c9f6f83.png)

I think the fact that EarTrumpet - and Windows itself, since both MS Teams outputs in the Windows' settings page for changing output devices had shown CABLE Input! - shows different device could be considered a bug, since it tries to switch, fail to do so (because of external reasons, like the program controlling the outputs itself with an iron hand) and reports back wrong information about the switch. I understand there might not be a method to check for it (maybe the program itself returns a "successfully switched output device" message), but if there is such a method and it's not implemented, it would be a nice-to-have. 
An error message ("Could not switch XYZ app's audio output device; have you checked if the application itself controls it?") would be preferable to wrong info.

**Comment by dobesv** [comment]
Another approach might be to update the messaging / docs /UI for EarTrumpet to just specify that it allows you to customize the outputs *for apps that don't support this themselves*

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (Will visit adding a FAQ or similar about this issue though as you suggested.) Feel free to keep the discussion going. Thanks!
