### ISSUE TITLE
Excessive Memory Use

### ISSUE THREAD

**Issue by cvigue** [File-New-Project/EarTrumpet#1243]
### Summary

While using the computer to do other things (VS Code, Wireshark, or just watch Netflix, doesn't seem to matter) the computer will suddenly start showing a lot of memory in use. Stopping various processes doesn't change much until I kill EarTrumpet. Killing EarTrumpet via Task Manager immediately frees around 10 or 15 GB (!) of memory and everything is OK. I can restart ET, and it does not immediately re-allocate that memory, but it will eventually start to bleed again. 

Typically it starts slowly growing and then after a bit, enters a state where memory use begins to grow rapidly. 

I usually leave my machine on for weeks at a time, often only rebooting when an update requires it, so it's been dying in the night for a few weeks now before I figured out why. This is a recent phenomenon and I've not changed my routine, the only changes would be updates to installed software including but not limited to updating ET. 

System:

Win 11 up to date, 32 GB of RAM, GPU, etc - nothing really exotic. 

I have VoiceMeeter also installed as well as OBS, but they seem well behaved. 

Note that asking ET to stop via right clicking the icon does not free the memory, it has to be killed with fire (find the process in Task Manager) to reclaim the lost memory. If you need more info/dumps/whatever I'll try to get them. I have uninstalled ET for now but it's a nice UI and I miss it a bit. 

### Steps to reproduce

Use the PC with ET running and wait for the crash. The PC will run out of memory and fault eventually, often in the middle of the night. 

### EarTrumpet version

Latest as of yesterday.

### Windows version

Microsoft Windows [Version 10.0.22621.521]

**Comment by riverar** [comment]
@cvigue Wow, something is definitely fishy there. I'm only at ~26MB for the whole week. If you don't mind, would be great if you could get it to a high number again then go to Task Manager > Create dump file, compress it, then send a copy to `team@eartrumpet.app`.

**Comment by cvigue** [comment]
OK I'll reinstall and see what I can do. The things I do for love! :D

**Comment by riverar** [comment]
Will close this for now, but feel free to return / re-open when you return.

**Comment by naqaden** [comment]
This happened to once months ago, despite regular use and daily reboots. I worked out it was [audio-related](https://stackoverflow.com/questions/73429856/memory-leak-on-windows-10-etwd-etwr), but otherwise had no idea it was Ear Trumpet.

Today it happened again, and I found killing Ear Trumpet freed the high memory usage, despite Task Manager not attributing this memory to the EarTrumpet.exe nor any other process. Then I found this issue, but it was too late to create the dump file. That was v2.2.0.0, so I updated to v2.3.0.0.

Within a few hours, it has happened again. I'm sending the compressed dump file.

**Comment by riverar** [comment]
@naqaden Standing by. Might be something in the audio stack (e.g. third party audio processing object) that's also causing the issue.

**Comment by brokedarius** [comment]
This happened to me as well I had to kill it because for the first time ever, it froze on me and when I went to the task manager I found it using 1.5gb of ram.

If it didn't crash I would have never noticed.

I will leave it running and if the high ram usage occurs again, I will try to zip you folks a dump.

**Comment by spacechase0** [comment]
I just noticed this is happening for me as well. I'm using a build with PR #1708 - I don't *think* my changes are doing this with how trivial they are, but I could be wrong.

It is currently using 9.5 GB of RAM, gaining at about 0.8 MB a second at the moment. This roughly corresponds to the last time my computer restarted itself (3 days and 21 hours according to task manager - not exact, but surprisingly close).

Interestingly as I was typing this, after I attached VS and paused the application to find a memory view, it was still increasing by 0.2-0.4 MB (occasionally slightly more) a second for a while even while paused. After a bit I noticed it went *down* to almost 5 GB and is now static.

(As I further did stuff while investigating with the app paused in the debugger, it did go a bit above 5 GB for a while, but is now at around 4.2 GB. I never unpaused the app either.)

It looks like wherever this is it's not on the C# side (and therefore not in EarTrumpet directly) but in native code, since a memory snapshot in VS reports only ~250MB used in managed memory. (This snapshot was taken after it had gone down to like ~5GB, but no idea why it went down in the first place since the app was paused the whole time.)

![Image](https://github.com/user-attachments/assets/e121f972-2d32-42aa-9ec5-a0b2befd1aea)

I don't know if this is related to my automated actions I mentioned in that PR or not. I did notice there are 342 (which has changed slightly while app is paused) (the only process with more threads is "System"=444, with "explorer.exe"=267 being the next) threads according to task manager, but visual studio is only showing 9, so unsure if that's relevant.

For reference, I restarted the app and it only has ~50 MB of memory in use and isn't constantly increasing at all, even after running through a couple actions triggered automatically (my launching minecraft one, and closing minecraft one).

(Another thing I don't know if is related but I noticed the automated action didn't run last time I triggered it (yesterday) but did today after I restarted the app, which is odd.)
