### ISSUE TITLE
Provide method to amplify audio beyond 100%

### ISSUE THREAD

**Issue by HunterGraubard** [File-New-Project/EarTrumpet#129]
I normally have my system volume at 30%, but some programs are just incredibly quiet and I need to turn those ones up specifically. The Windows volume mixer kind of supports it, but it turns up the system volume as well, kind of ruining the settings overall.

EarTrumpet doesn't seem to support this at all, so it would be nice if that could be added as a feature - but it'd be even better if it allowed adjustments without affecting the overall system volume.

**Edit:** If I'm not already being clear... I mean, for example, I'd like this kind of setup:

Device volume - 30%
Program 1 - 100%
Program 2 - 80%
**Program 3 - 200%**

Could something like this be achieved? Maybe the UI could allow us to click on the numbers and type in a value directly, instead of using the sliders - and this method could allow us to go beyond 100%.

**Comment by riverar** [comment]
What does 200% mean when Device Volume is set to 100% then? This is a really backwards way of using a mixer, it makes more sense to set your Device Volume to 60%, then Program 1 at 50%, Program 2 at 40% and Program 3 and 100%.

**Comment by HunterGraubard** [comment]
If the Device Volume is at 100%, then a 200% program volume would either be unavailable, or even better would amplify the program volume by 2x if possible. If you've ever used VLC Media Player, it has a similar feature, and it comes in very handy with media that is exceptionally quiet.

The issue is that some programs are just really quiet. With your suggestion of turning the Device Volume up and other Program Volume levels down, I need to turn down the volume for every single program that I ever use, just because of one specific program that needs to be turned up higher. If I ever run a brand new program, it'll default to the higher, louder (and more painful) volume, and I'll have to remember to manually turn it down each down.

**Comment by riverar** [comment]
Ok fair. So I think what you really need is a way to amplify audio past 100%. Would that help you out?

**Comment by HunterGraubard** [comment]
Yes, that would be wonderful.

**Comment by riverar** [comment]
I actually use this in VLC too, so can sympathize with you. 👍

**Comment by mkruselj** [comment]
Only if this is optional. I hate that feature in VLC, it can cause clipping way too often if not being careful about it.

**Comment by oott123** [comment]
Really want this feature, because "some programs are just really quiet".

**Comment by neilbalch** [comment]
Could we try to make this a feature soon? I'd really like to see it implemented and if informed how I can help, work on making it a reality in code.

**Comment by davuxcom** [comment]
I'm going to close this out with a solution.  We may take this someday but all evidence suggests this is a complicated audio processing feature that is out of scope for EarTrumpet.  (That said if Windows were to add some support we could change position).

What you can do (and what I always do) is use VoiceMeeter. You can use the free version, not the Banana version.

VoiceMeeter will act as a kind of proxy, you will set "Voicemeeter output" to the system device, then configure your headphones in VoiceMeeter under the A1 button (pick the WDM option).  Then, you can use the Voicemeeter control panel to boost the volume by moving these two red sliders:

![image](https://user-images.githubusercontent.com/1456216/58937472-5f11ff00-8727-11e9-9d75-ee26a17b9ba6.png)

(No further support for VoiceMeeter will be provided here--I just want everyone to have a solution as this is what I do when my headphones aren't loud enough)

**Comment by oott123** [comment]
@davuxcom I really understand that amplify audio past 100% it out of scope for EarTrumpet, but this issue, however, we just want some program's s volume to go beyond current volume on device.

like https://github.com/File-New-Project/EarTrumpet/issues/129#issuecomment-313919332 said:

> If the Device Volume is at 100%, then a 200% program volume would either be unavailable, or even better would amplify the Program Volume by 2x if possible.

I think amplify the Program Volume by 2x is out of scope for EarTrumpet, but It's good enough that if 200% program volume is unavailable. For example:

device volume - 30%
program 1 - 100% => 30% (on device)
program 2 - 80% => 24% (on device)
program 3 - 200% => **60% (on device)**

device volume - 80%
program 1 - 100% => 80% (on device)
program 2 - 80% => 64% (on device)
program 3 - 200% => **100% (on device, not 160%, we cap it to 100%)**

I wish you can reopen this issue and rename it, or I can open a new one, but we really want this feature. 

> The Windows volume mixer kind of supports it, but it turns up the system volume as well, kind of ruining the settings overall. https://github.com/File-New-Project/EarTrumpet/issues/129#issue-231896914

**Comment by davuxcom** [comment]
@oott123 Yes please file a new issue (it was mentioned in this thread but let's use this one for simply >100% possible output).  I'm a little confused by your example but I think you're talking about some of the features of the legacy mixer where you can move an app slider and have it change the device and other apps to do stuff. It's true that this was kind of opposite the intent of EarTrumpet, but it'd be good to capture your behavior in a different issue/feature request, because that's something that maybe the UI could incorporate in some fashion.  Thanks!

**Comment by andymerskin** [comment]
Sorry to necro this, but this is the only thread I found describing what I was looking for. Although, I have a slightly different suggestion for implementing this:

Why not provide a way to "amplify" by:
1. Providing a way to lock an app's volume (say it's at 100%)
2. Then, give us a way to reduce the volume for all other apps by syncing their volume levels if I adjust one of them

Or put another way, the workflow would be:
1. Check a "☑️ Sync app volumes" option in the main popover
2. Uncheck the app I don't want synced
3. Turn the volume down for the synced apps to something like 50%
4. Increase my master volume, which in turn, amplifies my unchecked app, which is still at 100%

For example, pretend I locked (or unsynced) Firefox here, and that I dragged 1 app's volume to 70, the rest of them would follow, instead of having to adjust each app to 70 individually.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/e653b102-c3f8-41c1-8de9-8d0fb213d948" />

**Comment by Camelotsmoon** [comment]
I'm not sorry for the necro post, as I fail to see how this is out of scope and the exact thing I went straight to eartrumpet for on my PC. This program is great because it's a lightweight version of what windows does, but better because it helps me manage my audio devices in an easy way... This is the exact thing I assumed eartrumpet could do without needing to pull out some ridiculouly complicated tool like bananameter or something, and I was extremely disappointed it could not do it.
