### ISSUE TITLE
Remove AppInstaller

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#1502]
Re: https://www.microsoft.com/en-us/security/blog/2023/12/28/financially-motivated-threat-actors-misusing-app-installer/

Microsoft has again disabled a critical component of the appinstaller technology--URL scheme activation--making it an unreliable channel for delivering software. We are no longer using appinstaller moving forward and must remove it from our pipeline.

We will continue to evaluate whether we keep using MSIX and Desktop Bridge (fka Project Centennial). (The technology transfer of MSIX to Microsoft India does not instill confidence.)

**Comment by iAvoe** [comment]
Currently Microsoft Store is down, so currently there is no way to update or download current builds, guess I'll try compile one...

**Comment by shodanx2** [comment]
Hello,
Please provide temporary instruction for offline manual install
For both stable and dev version (since dev version has the much needed actions feature)

Here is how I do the installation at this point


### Install stable version 2.3.0

https://packages.chocolatey.org/eartrumpet.2.3.0.nupkg

using 7-zip, uncompress the file into its own folder as if it were a zip file

Decompress the file eartrumpet.2.3.0\tools\release.zip

Rename the "release" folder to "EarTrumpet"

Copy this folder to 

C:\Program Files or %PROGRAMFILES%\

Create a shortcut from 

C:\Program Files\EarTrumpet\EarTrumpet.exe

to

C:\Users\user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

or 

%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup

Eartrumpet stable version 2.3.0 should now start automatically on reboot


### As for the dev version

Download

https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

open this file with a text editor, you will find two more URLs to download

https://install.eartrumpet.app/dev/EarTrumpet.Package_2.3.0.15_x86.appxbundle
https://aka.ms/Microsoft.VCLibs.x86.14.00.Desktop.appx

download EarTrumpet.Package_2.3.0.15_x86.appxbundle

decompress like a zip into it's own folder

In this folder you will find 

EarTrumpet.Package_2.3.0.15_x86\EarTrumpet.Package_2.3.0.15_x86.appx

decompress this file

You will find EarTrumpet.Package_2.3.0.15_x86\EarTrumpet.Package_2.3.0.15_x86\EarTrumpet

Copy this folder to 

C:\Program Files or %PROGRAMFILES%\

Create a shortcut from 

C:\Program Files\EarTrumpet\EarTrumpet.exe

to

C:\Users\user\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

or 

%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup


Now one weird thing for me, even though I am on version 2.3.0.15

![image](https://github.com/File-New-Project/EarTrumpet/assets/10621885/8f4c9dfb-3ad1-4283-820a-bc51daccb0b6)


I do not have the "actions", so I cannot create hotkeys to switch my audio between my TV's speakers and my headphones !

Not sure what the problem is at this point.

![image](https://github.com/File-New-Project/EarTrumpet/assets/10621885/ddfec82c-f015-4b7b-9819-a9a1dc08d495)

**Comment by brunetton** [comment]
THANK YOU !! This saved my life today ! Using a VM that is not connected to the internet (and won't be). This is super simple and should absolutely be documented somewhere ! 

@riverar still "NO" loud and clear ? (ref to #1013) Aren't you opened to a link to this issue in the README ?

**Comment by riverar** [comment]
Coming soon, I have the shiny new pipelines nearly ready. Thanks for your patience!

**Comment by brunetton** [comment]
This is definitely a GREAT news ! Thank you
