### ISSUE TITLE
Version 1.4.4.0 doesn't launch

### ISSUE THREAD

**Issue by SW1FT** [File-New-Project/EarTrumpet#156]
I'm using Windows 10 with the latest updates and since updating EarTrumpet to 1.4.4.0 from the Microsoft Store it just simply doesn't launch. Is there a way to force it or to fix this?

EDIT 1: Ops, I didn't install 1.4.4.0, I installed 1.5.0.0.
EDIT 2: Uninstalling and installing it back "fixes" this.

**Comment by TzarAlkex** [comment]
I think I had the same problem. EarTrumpet wasn't working today, saw in the Store downloads that it had updated to 1.5.0.0 today.
I fixed it by resetting the app instead of uninstalling. You should probably reopen issue because if the update is broken for us two there is probably a lot of other people it also broke for. There might be a bigger issue worth looking at.

**Comment by GoldenTao** [comment]
We saw a bunch of odd issues with the 1.5 versions that might have caused this.

Let us know if you're still seeing the same issues with the latest version 1.5.2.0

**Comment by SW1FT** [comment]
The latest version launched just fine after installing.
