### ISSUE TITLE
Please give us the option to choose the icons for ear trumpet in the notification tab

### ISSUE THREAD

**Issue by Ownsin** [File-New-Project/EarTrumpet#160]
Hey, I noticed you changed the icon for ear trumpet to that of the default volume control for windows. Please make it so we can go back to the old one. At least give us the option to do so! having both on the same tab is confusing because they both look the same :/. I have no idea why you even changed it. It was fine as is.

Thank you.

**Comment by BOTButtcheeks** [comment]
I concur, I need to use the default Icon a lot anyway with features that aren't a part of ear trumpet.
if you could have an option to choose between the two that would be great.

**Comment by riverar** [comment]
What features do you use? We plan on adding all the context menu items from the original onto EarTrumpet -- would that help?

**Comment by Ownsin** [comment]
Just give us back the old icon or the ability to put back the old icon.

**Comment by riverar** [comment]
Why?

**Comment by Ownsin** [comment]
Because you changed the icon to look exactly like the icon for the default volume control for Windows and having both look the same confuses me. I want to have the ability to put the old icon from eartrumpet so I stop confusing both. Here's an example: http://ownsin.net/i/aa58a.png

**Comment by riverar** [comment]
Turn the default one off.

**Comment by Ownsin** [comment]
I still use it. Just like the other user mentioned. We still use both.

**Comment by riverar** [comment]
What features do you use in the default one?

**Comment by Ownsin** [comment]
Getting to the playback and devices settings pretty quick from there. Eartrumpet doesn't have that.

**Comment by riverar** [comment]
That's fair. We'll add that ASAP. Thanks.

**Comment by Ownsin** [comment]
Thank you!

**Comment by BOTButtcheeks** [comment]
You also have to note that if Microsoft decides to add features to the default audio icon then we will have to wait for you to update to receive those features

Not to mention certain sound drivers hook into that context menu and you cant expect to add compatibility for everything in existence which adds it.

If you want to use a speaker icon then use a different one because I'm going to keep both no matter what.

**Comment by riverar** [comment]
@BOTButtcheeks Can you provide an example of a driver hooking into that menu?

**Comment by BOTButtcheeks** [comment]
I personally have "spacial sound" on my context menu provided by my driver.

It still does not negate the fact that if MS comes out with features your users will either be left behind while you work on it, have to be confused between the two icons or just hide your app back in the extended menu where the software will take away the convenience this app provides.

**Comment by riverar** [comment]
Spatial Sound is provided by Windows. We'll implement the context menu items. Would that satisfy everyone? We are not interested in restoring the old icon.

**Comment by Ownsin** [comment]
But you said you would earlier? I want the old icon back or honestly I'll stop using the app itself entirely.

**Comment by riverar** [comment]
We got some feedback that says "The stock Windows one controls the absolute system volume. The EarTrumpet one controls the relative volume of varous applications."

I want to make it clear that this is completely wrong. EarTrump has, since inception, allowed users to control both the device volume -- same as Windows -- and application session volume.

**Comment by igvk** [comment]
I personally think that Ear Trumpet can theoretically replace Windows stock audio control, if all the menu items from stock can be added.
But as far as volume adjustments are concerned in its current state, there are some ergonomic issues:
First, adjusting system volume requires moving mouse to the top of the popup list - it would be much better to have it as close to the tray icon as possible (meaning placing it at the bottom).
Second, there is no indication of the currently selected audio device in the main popup (it's seen only in right-mouse-button menu) - which would be convenient when you have several audio outputs.

**Comment by nebbors** [comment]
I will not remove my current volume control from windows.
Give me the option to use a different icon, or I will have to remover ear trumpet. I only use it to quickly switch sound output devices.

**Comment by ElvenSpellmaker** [comment]
To answer @riverar's question and add my two cents:
I'm really happy the icon is now live and the same as the Windows icon (but you could add a toggle for those who wish to have it static/a trumpet)

The only feature for me now missing from ear trumpet is the ability to switch audio devices and see which one is currently the active one:
![image](https://user-images.githubusercontent.com/2286713/33741945-3f1ee2ac-db9e-11e7-9ac2-9dab3fbf07af.png)
![image](https://user-images.githubusercontent.com/2286713/33741952-44ceaf34-db9e-11e7-8a27-ff6c4fa820e9.png)

Clicking on another audio device will route playing audio through the chosen device.

I agree with @igvk that the main volume should be as close to the bottom as possible, and if the device switcher is added that'd also be placed just above the volume, so effectively in my view it'd be:
-- Application 1
-- Application 2
-- Current Device ^
-- Main volume

And then after expanding the devices menu it'd be:
-- Application 1
-- Application 2
-- Select Playback Device v
--- Device 1
--- Device 2
-- Main volume

So effectively it'd be like the default volume mixer in Windows 10 with the _addition_ of the EarTrumpet features on the top.

**Comment by GoldenTao** [comment]
Hi all, the other EarTrumpet dev here.

Looks like this thread has jumped all over the place, so lets clear a few things up...

@ElvenSpellmaker @igvk Thanks for all the additional feedback, probably best if we can keep each thread for one item though so we don't have split conversations happening.  I've pushed that feedback to this thread: https://github.com/File-New-Project/EarTrumpet/issues/165

For the main issue of this thread, EarTrumpet was created because we couldn't turn down the Xbox app or background music while being on a Skype call. The initial purpose was to totally replace the need to use the Windows volume control at all and hopefully replace some of the need to use the Windows volume mixer.

We did take a bit of time to get the icon changed over to the live system, but that has always been the idea; while also being our most requested feature both here on GitHub and through the Feedback hub.

By default, we are going to keep the Windows icon and it's ability to show the volume or mute status on the icon as that is the main goal of EarTrumpet.  We will add an option so that if needed, you can switch back to the old static icon.  We've been working on something that will let us directly show the volume control menu, but that is still in an investigation phase at the moment.

Thanks for all the feedback, we do read it all, looking at you Bob.. on the Feedback hub, Windows Store review and Github :)

**Comment by Ownsin** [comment]
So when will we be getting the option to use the old static icon? because that's all I care about.

**Comment by andydavies92** [comment]
@Ownsin, well you could always check-out an old commit before the icon was changed, build it yourself and deploy it to your machine? This is an open-source repository after all :P

**Comment by Ownsin** [comment]
I would do it if I knew how, but I don't. I'm just your typical user :/

**Comment by paulcee** [comment]
There might also be copyright implications in "borrowing" an icon from Microsoft, even if you're extracting it from an OS DLL rather than bundling it in your own package.

**Comment by Kesmy** [comment]
@paulcee I think you're looking for:

"Microsoft product icons are the thumbnail-sized images indicating that a Microsoft product has been installed on your operating system. Icons may not be used[...] in online and Internet locations, in software applications, [...]." - https://www.microsoft.com/en-us/legal/intellectualproperty/permissions

**Comment by riverar** [comment]
Thanks for the concern but we're okay on this front.

**Comment by GoldenTao** [comment]
The option to change the icon back to the original EarTrumpet icon is now available in the latest store version (1.5.2.0)

**Comment by Ownsin** [comment]
Finally! thank you very much for listening to me and the others.

**Comment by lyonharted** [comment]
For me, I switch between headphones, surround sound, and speakers VERY regularly for meetings, watching movies, so on on my PC. I can change sound device on the Windows audio button, but NOT on EarTrumpet.
