### ISSUE TITLE
Feedback items from @ElvenSpellmaker & @igvk

### ISSUE THREAD

**Issue by GoldenTao** [File-New-Project/EarTrumpet#165]
Original feedback items split from other thread: 
- https://github.com/File-New-Project/EarTrumpet/issues/160#issuecomment-350116604 
- https://github.com/File-New-Project/EarTrumpet/issues/160#issuecomment-350096630

Thoughts
- The tooltip is being updated in an upcoming version
- Showing the current audio device in the main UI is coming in an upcoming version
- We've had a bunch of discussions around whether the system/device volume should be at the top or bottom and generally believe that it would break the hierarchy of system/device volume being an overarching control of the apps below it.
- With the expansion showing multiple devices, on some PC's this might work okay, but for some users they have 5+ devices which would make that area very busy. We're looking into other ways to do this from the UI, but they will likely look a little different to the current Windows implementation of changing default device.

**Comment by igvk** [comment]
The idea to place system volume closer to the tray icon is due to usability - the most common operation is adjusting system volume, so it needs to be as fast as possible and most automatic, without extra effort to move the mouse to the top of the UI.
If the system tray is positioned at the top, then system volume may be at the top, too.

**Comment by Ernest314** [comment]
The visual hierarchy of a UI doesn't solely go from top to bottom. I agree that in this case, since the system volume is clearly delineated (currently via a highlight but could be equivalently done via a separator), it would be completely intuitive to have the overarching control be on the bottom.

Examples in other products: hamburger menu being at the bottom (readit on WP), navigation buttons being at the bottom (android), taskbar being at the bottom (windows).

**Comment by riverar** [comment]
EarTrumpet 2.0 is out. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
