### ISSUE TITLE
Dragging the master volume bar glitches

### ISSUE THREAD

**Issue by mitom** [File-New-Project/EarTrumpet#187]
Steps to reproduce:
1. Open the EarTrumpet mixer panel by clicking on the icon in the taskbar.
2. Click and hold the vertical bar on the master channel.
3. Drag the bar to either direction with decent speed.
4. Release the bar.

It's easiest to see the effect if you quickly drag it to either end and then immediately to the other.

What I see happen is the bar slowly (as in similar speed as if I were using my mouse scroll to move it) moving in the direction it was dragged in, lagging behind the cursor. The volume changes at the same speed. Dragging it quickly left and right causes it to first slowly go one direction and then the other. It will often glitch back-and-forth between the location the mouse cursor is at the moment, and the location it was a moment ago:
![2018-03-07_12-46-48](https://user-images.githubusercontent.com/3754515/37093041-d2ad8be2-2205-11e8-97ef-c4bb0a46673a.gif)

It only happens to the master volume bar, it doesn't happen to the application sliders.

**Comment by riverar** [comment]
Yep, I've been dragging my feet on fixing this. Should have a fix around this weekend.

**Comment by Silver2410** [comment]
As you perfectly know, this also happens when using the mouse's scroll wheel.
Also, although I don't use the touchpad, scrolling with it seems to not work well (mentioning here, but can open a new ticket if this helps you to keep everything more organized).

PS: Thank you for your work, much appreciated (I'm using EarTrumpet for several months and I LOVE IT, keep it up!)
