### ISSUE TITLE
Localization Needed for 2.0.0.0

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#199]
We need help translating some text for an upcoming release of EarTrumpet 2.0. This time we're trying a collaborative editing platform https://osqwaxf.oneskyapp.com/admin/project/dashboard/project/146899. If you don't see your language, let me know and I'll add it.

Thanks a bunch!

cc: @Simizfo @yinyue200 @vzczc @pablojimpas @Craftuser5000 @haefele @adescre

**Comment by yinyue200** [comment]
I have translated for Chinese.
By the way, the website is nearly impossible to be loaded in China because the government block Google and some CDNs if people in China don't use a proxy.
![firefox_2018-06-08_12-53-01](https://user-images.githubusercontent.com/13848771/41140518-937ed188-6b20-11e8-9dc2-5a72322c5d60.png)
![firefox_2018-06-08_13-00-22](https://user-images.githubusercontent.com/13848771/41140519-93bc5aa8-6b20-11e8-8fd7-20beb2080dec.png)

**Comment by riverar** [comment]
Yikes, sorry about that. I'll pass that on to them ASAP. Anyone: If you need me to paste the original strings here, let me know.

**Comment by Alex229Qc** [comment]
French is translated! :)

**Comment by Alex229Qc** [comment]
French has been translate! :)

**Comment by apetriceanu** [comment]
Romanian is done!

**Comment by pablojimpas** [comment]
I've just translated it to Spanish 👌

**Comment by Blizzardfall** [comment]
I have added Korean translation.

**Comment by riverar** [comment]
Thanks again all, will add any additional languages to the next release.
