### ISSUE TITLE
Scroll anywhere to change volume when eartrumpet is open

### ISSUE THREAD

**Issue by KLuuKer** [File-New-Project/EarTrumpet#208]
I want to be able to just open the menu and scroll everywhere else to change the volume
Just like with the stock windows volume control

![volume-scroll](https://user-images.githubusercontent.com/12729178/41371921-1951ef64-6f4c-11e8-854e-bf2bc01f5ff2.gif)

**Comment by do-bo** [comment]
I found interesting behaviour/bug related to this - scrolling anywhere changes volume but it also scrolls the window under the cursor.

To reproduce: Have at least 2 playback devices. Unfold the devices flyout (if only the default device is shown). Fold the full list back so that only the default device is shown again. Now you can scroll the volume with mouse cursor anywhere, but anything under the cursor is also being scrolled.

**Comment by riverar** [comment]
Yep got it, thanks!

**Comment by Epicoss** [comment]
Or if that isn't an option make it that you can scroll to change the volume when the cursor is on the start bar intead of on the ear trumpet icon. It isn't that practical to have such a small area.

**Comment by b82a** [comment]
Very much needed

**Comment by Tester798** [comment]
@b82a you can try my implementation of this (and few other) function at https://github.com/Tester798/EarTrumpet/tree/dev-custom

**Comment by vertigo220** [comment]
As long as this is optional, because I *hate* that "feature" of Win10. I'm constantly changing the volume accidentally while trying to scroll something else, since this behavior is completely contrary to the standard. In fact, they _finally_ added the ability to scroll background windows in Win10, something I had to use a 3rd-party app for in 7, and then they implement this behavior, which doesn't follow that option's setting. Typical M$...

Anyways, I'd suggest you check out 7++ Taskbar Tweaker, which has the option to adjust the volume when scrolling over the notification area or the entire taskbar, as well as many other very useful features that should be built in to Windows.
