### ISSUE TITLE
Suggestion: Add option to toggle spatial sound on playback device

### ISSUE THREAD

**Issue by alessiocpt** [File-New-Project/EarTrumpet#212]
I sometimes enable spatial sound while watching movies or playing games with headphones. Is it possible to add a button to toggle it on and off? It could be visible only on right click on a playback device.

Thanks a lot for your work!

**Comment by Zoneykid** [comment]
Would like to request this as well since now windows has 3 Spatial Audio renderers (Dolby Atmos, DTS:X, and Windows Sonic)

**Comment by red9350** [comment]
+1, I'd also like to have Windows' Spatial sound context menu replicated in EarTrumpet, so I could finally hide forever the System sound tray icon.

![image](https://user-images.githubusercontent.com/16651290/74430140-98753f80-4e5c-11ea-9f04-26ee6a9295eb.png)

**Comment by mcbexx** [comment]
Add another one to the request pile. With Windows Sonic being free it's a very common feature to use when gaming with headphones. Being able to quickly switch it on and off would be great.

Bonus points if it would switch the device in question back to 5.1 when you turn Windows Sonic off again. I have no idea why Windows would not behave like that by default.

**Comment by kokomugi** [comment]
Hopefully, this will be implemented

**Comment by DaedalusBLN** [comment]
+1

Having a quickly accessible Spatial sound toggle is a crucial for me. As a Dolby Atmos for Headphones user, when using VLC to playback certain multichannel audio media files, I've had EXTREMELY LOUD bleeps coming out of my speaker instead of the file to be decoded normally. Switching DAfH off was the only way for these files to be played normally, so having quick access from the tray would make my life easier. Another usecase is when doing audio production work, you certainly want these effects to be off before digging in your DAW.

Thanks for all your efforts so far, gave you 5* on Windows Store, well deserved!
