### ISSUE TITLE
Applications not always recognised by EarTrumpet

### ISSUE THREAD

**Issue by maglax** [File-New-Project/EarTrumpet#284]
Issue:

For some reason, EarTrumpet will not recognize applications in volume mixer, and no audio will be heard. This issue has occurred more than once for me, with different applications being affected.

First occurrence:  Mozilla Firefox, Spotify web desktop player.
Second occurrence: Google Chrome

I have not been able to reproduce this problem on my other computers.

System:

Windows 10
Speakers: Monitor speaker on HDMI, headphones on standard audio jacks.

**Comment by GoldenTao** [comment]
Are those applications making sound at the time? Ear Trumpet will only pick up sessions that are active and playing sound.

**Comment by TheEx1leGrays0n** [comment]
I've been experiencing this issue with Firefox the only workaround I have is to restart my pc. But it only works until I restart my pc then the issue flares up again.

**Comment by ChaosDerivat** [comment]
I also experience this issue with Firefox. E.g. a youtube video is playing but EarTrumpet will not show firefox as a sound source. When I restart my pc it will work occasionally fine until I restart it again. But most of the time it is not working.

Windows 11 and Firefox 109.0 (64bit)

**Comment by Dreezby** [comment]
If you still have the problem, this is a fix that i found in another thread and worked for me:

[davuxcom](https://github.com/davuxcom) commented [Aug 6, 2019](https://github.com/File-New-Project/EarTrumpet/issues/403#issuecomment-518824533)

Type Win+X, select Settings and thenSystem -> Sound -> App volume and device preferences.

This page lets you set the output for apps or clear the system configuration (Reset button at the bottom). You can use the Reset button to fix your issue if the TV output device isn't available.

We use the same API to change devices, and Windows has some known bugs around this device redirection scenario. In this specific case I think the expectation is that Firefox would detect that it has a persisted output which is currently unavailable, and clear it (causing the audio to go to the default device). But due to the way Microsoft rolled out this functionality, apps don't expect to need to do this and thus don't.

From an EarTrumpet perspective, we don't know that Firefox is even playing audio since the audio stack hasn't told us anything about Firefox, so I'm not seeing any good way to mitigate this behavior right now.
