### ISSUE TITLE
In-game Mic sound stuck on default!

### ISSUE THREAD

**Issue by MelonCity** [File-New-Project/EarTrumpet#287]
Hi,

I want to start by saying how amazing this software is, I love it! I have a slight issue I was hoping I can get some insight about.

I'm only able to hear the mic of others in the game through my speakers and not through my headphones.

For example, if I'm playing Fortnite, I'm able to toggle the game sound from speakers to my headphones for example and vice versa. However, when I toggle from speaker to headphone, the mic remains coming out of the speakers and I'm unable to hear it through my headphones; while the game sound only plays through the headphones. switching back plays both through the speaker. 

Other games such as CS GO, I'm unable to play neither game or mic sounds through my headphones. Eventhough EarTrumpet shows that my headphones are selected.

I attempted changing my "default" sound device and no luck there.

any idea if I can fix this? I appreciate any insight and input. This software comes closest to what I need to do and would love to figure this out.

Regards,
Jay

**Comment by toastido** [comment]
For comms in Fortnite, you need to set your default communications device within windows to use your headset.  This is due to a change by MS and not an EarTrumpet bug. 

To set, go to playback devices, right click on your headset, and select "Default Communications Device".  Do the same in the recording tab, and your in-game chat will begin working through your headset.  This might fix CSGO if they rely on the same setting.
