### ISSUE TITLE
Ghost window appears in task switcher after switching from tablet mode to non-tablet mode.

### ISSUE THREAD

**Issue by ruifung** [File-New-Project/EarTrumpet#294]
It goes away after I open and close the eartrumpet flyout.

![screenshot 1](https://user-images.githubusercontent.com/1073945/46264984-f4d00b80-c554-11e8-8961-d47c7a844a2e.png)

**Comment by GoldenTao** [comment]
Thanks for the report, we'll look into this one.

**Comment by ruifung** [comment]
Yes, and 2.0.7.0

**Comment by dean1012** [comment]
Sorry to reopen but this issue is still present. Running version 2.0.8.0 on Windows 10 1809 17763.316.

Have EarTrumpet open. Activate tablet mode. Deactivate tablet mode. EarTrumpet now shows a phantom window in task switcher. Opening the flyout removes the phantom window until tablet mode is activated again.

**Comment by riverar** [comment]
@dean1012 Can you still reproduce this in 2.1.1.0? If so, please re-open. Looks fixed.
