### ISSUE TITLE
When moving mouse on tray icon, mouse wheel does not work anymore

### ISSUE THREAD

**Issue by Matt-17** [File-New-Project/EarTrumpet#303]
When I click on the tray icon, I can change the master volume with my mouse wheel. But as soon as I move the mouse a bit (by accident) it's not working anymore. 
Is this considered as bug and fixable? 

Also it would be nice to change volume always by mouse wheel over the icon even without clicking (as there are already suggestions).

**Comment by riverar** [comment]
Hey Matt, we battled internally about this for weeks and concluded it made most sense to make this intentional design change (earlier in the year). It cleaned up a bunch of weird scenarios, such as users opening EarTrumpet and moving the mouse (accidentally or otherwise) to a window with scrollable content under the cursor.

Good news though: A future release of an EarTrumpet add-on will allow additional entry points that will offer methods of changing the device volume, stay tuned!

Will close this for now.
