### ISSUE TITLE
EarTrumpet not showing up in system tray

### ISSUE THREAD

**Issue by CybranM** [File-New-Project/EarTrumpet#314]
Whenever I start my system EarTrumpet doesnt show up in the system tray, I have to kill the process and manually start it again. When it then starts theres now two icons in the system tray, one of which goes away on mouse over.
Has anyone else experienced this issue? I tried searching but nothing showed up.

**Comment by CybranM** [comment]
Yes, I'm sure. The regular windows sound icon is still there but EarTrumpet isn't (until I stop the process and start it manually)

**Comment by riverar** [comment]
@cybranM Can you record a video? Screen to Gif is pretty easy to use. https://www.screentogif.com/

**Comment by CybranM** [comment]
It doesn't seem to happen every time after I re-enabled automatic start on EarTrumpet but I'll capture a short video next time it happens

**Comment by CybranM** [comment]
It's weird, whenever I try to record a video the icon shows up. It appears to me, a layman, as if the system tray needs to be "refreshed" for the EarTrumpet icon to appear. I tested this by right clicking and closing another system tray app and when the system tray "refreshed" the EarTrumpet icon would show up.
I'll try to capture it with my phone next time to show whats happening.

**Comment by riverar** [comment]
Hey @CybranM no hard feelings, going to close this until you nail this down. Trying to tidy up our issues list, thanks. Feel free to re-open when you're ready.

**Comment by auspicious108** [comment]
I had a similar issue and any fixes, including completely reinstalling the app didn't work. 
But I managed to fix it myself with a workaround. There is a Windows bug that hides the last tray icon.
So any rightmost icon in tray is hidden on my system (windows 10) for whatever reason. Can't access it at all unless I put something else in there.
And since I used to have EarTrumpet at the right, it was hidden. I blamed the program for this, but it's innocent.
Anyway, I just put some useless icon in there and had no issues ever since. Default Windows volume mixer is a good candidate.

Hope this will help some soul with a similar issue.
