### ISSUE TITLE
Instructions in COMPILING.md do not result in a successful build.

### ISSUE THREAD

**Issue by Nytohan** [File-New-Project/EarTrumpet#320]
Following the build instructions in COMPILING.md results in a failed build with the following errors:

![afbeelding](https://user-images.githubusercontent.com/10177148/49341288-77577300-f64b-11e8-8095-90bf36a4029d.png)

**Comment by riverar** [comment]
Can you screenshot the Visual Studio installer showing that `Windows 10 SDK (10.0.14393.0)` is installed?

**Comment by Nytohan** [comment]
Sure can.

![image](https://user-images.githubusercontent.com/128048/50544853-b4b21080-0bb7-11e9-91d8-4a67edb49286.png)

**Comment by riverar** [comment]
Works in my VM but I can reproduce the issue. The `<HintPath>` in EarTrumpet.csproj is relative and isn't backing up far enough in certain cases (e.g. if the EarTrumpet code is on the desktop). It will only go back 4 levels before assuming it's on the root of the OS drive. I'll get this fixed in dev.

Workaround: Edit EarTrumpet.csproj and change line 81 (https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/EarTrumpet.csproj#L81) to:
`<HintPath>C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd</HintPath>`

I'll look into a more permanent fix.

**Comment by riverar** [comment]
@Nytohan No problem, thanks for trying it out and finding the bug!
