### ISSUE TITLE
Request: Control volume of a specific program with hotkey

### ISSUE THREAD

**Issue by DracoClaw** [File-New-Project/EarTrumpet#363]
So i just found this and im in love, my only qusetion is if i can control the volume of a specific program with a key or even better the volume scroll on my keyboard.

**Comment by lukaszelinka** [comment]
This feature would be even better if you could use a midi board with faders/nobs (like the behringer x-touch mini) to control the different programs by turning the knobs. or at least have a interface so we can create plugins to do that

**Comment by m0ck0** [comment]
pleaaaaaaseee, this would make the app just perfect

**Comment by Packetdancer** [comment]
FWIW, I have a personal fork of EarTrumpet that lets me do basically this, including using modifiers with the keyboard volume control; you can target either a device or an application ON a specific device. The only aspect of this that it doesn't handle right now would be adjusting the volume of an application _regardless_ of what audio device it was on.

https://raw.githubusercontent.com/Packetdancer/EarTrumpet/master/Graphics/hero5.png will show what I mean. 

Mostly I just did it because I wanted this functionality myself; I can adjust the volume of, say, Discord and a game that I'm streaming individually this way. But I'd be happy to make a pull request to contribute it back, if others think it would be useful. Though admittedly the architecture to preserve the volume target functionality even when an application has been exited and restarted got a little more tangled than I originally expected; it could probably do with some cleanup.

**Comment by DracoClaw** [comment]
Would i be able to use the volume scroll wheel on my G910?

**Comment by Packetdancer** [comment]
I actually wrote the fork with a Logitech G910 Orion Spark as my keyboard, though I replaced it with a Corsair K95 last week. (Yay new keyboard!) So I think it's safe to say that while the forked version of EarTrumpet _should_ work with every keyboard's media controls, I can _guarantee_ it works with only two, and the G910 is one of them. ;)

**Comment by DracoClaw** [comment]
Oh! That's amazing, Id love to try that out!

**Comment by DracoClaw** [comment]
@Packetdancer I never heard back from you, but how could i go about using your version?

**Comment by DracoClaw** [comment]
Update: Ive been using their fork for a while and its very good
