### ISSUE TITLE
EarTrumpet tray icon fly-out disturbing running full-screen apps

### ISSUE THREAD

**Issue by GoldenHashtag** [File-New-Project/EarTrumpet#373]
how to reproduce :
1, open any Windows app (settings, groove music, calculator, etc)
2, press Windows + Shift + Enter
3, now open tray icon fly-out
you'll see the full-screen app is automatically minimized.

**Comment by davuxcom** [comment]
Thanks for reporting, we didn't know about this hotkey to fullscreen modern apps.

The way the system works, our desktop window (along with OneDrive and others, but not the system flyouts like Sound and Network) minimizes fullscreen modern app windows.  In order to get around this we'd need to create our window in such a way that not available to our app anyway.  This is basically a Windows bug.

**Comment by GoldenHashtag** [comment]
> Thanks for reporting, we didn't know about this hotkey to fullscreen modern apps.
> 
> The way the system works, our desktop window (along with OneDrive and others, but not the system flyouts like Sound and Network) minimizes fullscreen modern app windows. In order to get around this we'd need to create our window in such a way that not available to our app anyway. This is basically a Windows bug.

but task manager isn't part of explorer either.
when you enable Always on top in task manager it will draw on top of full-screen apps and will not disturb them even if clicking on it, and unless it's made possible with undocumented API i believe there is a workaround for it.
