### ISSUE TITLE
Changing Chrome volume causes 100% CPU usage of Eartrumpet

### ISSUE THREAD

**Issue by makedir** [File-New-Project/EarTrumpet#395]
Changing Chrome volume causes 100% CPU usage of Eartrumpet, then randomly stuck and freezes, tehn also randomly causes Realtek background process to be stuck too and take 50% CPU.

**Comment by davuxcom** [comment]
When this happens, collect troubleshooting info (Settings / General / About).  Is there anything repeating in the log?

**Comment by makedir** [comment]
Sadly I had restarted the tablet afterwards I will look if I get the issue again.

**Comment by davuxcom** [comment]
If you've only seen this once, then this definitely sounds like audio service nonsense that can be caused by a myriad of factors. If you come up with something repeatable please let us know.  It does sound like this is a configuration-specific issue that EarTrumpet may have just been a further symptom of, though.

**Comment by ericrbg** [comment]
So, it quietened down as soon as I opened it up to get troubleshooting infom, but I've finally got some logs for this issue: https://gist.github.com/ericrbg/acc2e8f904e9060bee1b61b489c22456

**Comment by davuxcom** [comment]
That's a pretty curious log. We're getting events over and over for sessions that are already invalid (AUDCLNT_E_DEVICE_INVALIDATED).
