### ISSUE TITLE
How is EarTrumpet's UI created?

### ISSUE THREAD

**Issue by OdinTech3** [File-New-Project/EarTrumpet#408]
Hello, I am newbie into c# and when I saw the ear trumpet i was amazed as to how a third party app could look so natively windows 10.

I has inspired me to create something with the same UI approach as EarTrumpet has. I would like some guidance as to how you guys were able to create the UI for your UWP to show up from the system tray the way EarTrumpet does.

Would really appreciate your guidance, thank you.

**Comment by davuxcom** [comment]
Hi @OdinTech3, we appreciate the compliment. :)  EarTrumpet is a C#/WPF app that is designed to fit in with the system.  Where possible EarTrumpet should be indistinguishable from the system UI.

Microsoft builds their system UI using UWP/XAML and some proprietary components used to isolate the application window and control its presentation based on various user actions.

I see you've done a bunch of stuff on your GitHub, so I'm assuming you're looking for this information:
- Using WPF XAML instead of UWP XAML will let you have full control over your window positioning and frame, as well as the app lifecycle.  WPF XAML and UWP XAML are very similar but run on different sets of frameworks.
- We're using a UWP "Centennial" app, which is a packaged desktop app delivered through the Windows Store.  If you open up `EarTrumpet.vs15.sln` with Visual Studio, you'll be able to have the same experience without dealing with any packaging.  EarTrumpet is ultimately a plain C#/WPF app.
- WPF ships with Windows 7-era styles, matching the look and feel of Windows 10 requires you to modify each template.  You can source some information from the UWP `generic.xaml` file, and then re-style and re-template controls to get them to look exactly the way you like.  This took some effort, and our styles aren't prefect, but everything in EarTrumpet is visually custom, but using all the same logical controls like `Slider` and `TextBox`.  
- You may find some useful info in our [Technical documentation](https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/README.md)

If you start at `App.xaml.cs`, you may be able to get a sense of how the app is laid out.  Our tray icon is created using `ShellNotifyIcon` (you could use `System.Windows.Forms.NotifyIcon` to simplify), and this click event causes `FlyoutWindow` to be displayed.  If you look at `FlyoutWindow.xaml.cs`, you can see how we communicate with the Taskbar and then decide where to display the window.

**Comment by OdinTech3** [comment]
Thanks so much for the detailed response, I am excited to dig in and learn about building windows apps. Is there a slack, discord, or gitter channel set up in the case I would like to ask more questions. Thank you!!
