### ISSUE TITLE
Skype has two instances of volume settings

### ISSUE THREAD

**Issue by che0522** [File-New-Project/EarTrumpet#42]
One of them is always full and seems to do nothing.

**Comment by riverar** [comment]
Thanks, I have this issue too. Need to investigate more and coalesce the streams where possible.

**Comment by riverar** [comment]
Further investigation needed -- EarTrumpet is working correctly and showing N instances with different grouping IDs and session IDs, e.g.:

Display Name: Skype.exe
Session ID: 3758969452
Grouping ID: a381a841-23a0-4ef9-8a97-081aa1cd7102
------
Display Name: Skype.exe
Session ID: 2452688569
Grouping ID: a7f41ea9-d0f6-4474-b3af-f1103bf9a7ba
------
Display Name: Skype.exe
Session ID: 2329746590
Grouping ID: 1eec994b-9355-4858-8f1d-2a01832840dc

According to MSDN, SndVol should not be grouping these instances due to differing grouping IDs. But alas, SndVol is so we need to take a peek inside. Might be a plat bug or some sort of unique behavior for Skype.

**Comment by gizmo179** [comment]
Mine is showing 3.

**Comment by jssshashi** [comment]
Mine shows 3 
I think I know the reason. Think it like skype on your phone 
1.  the speaker phone (volume thru the bottom speaker in a phone)
2. the volume call ringer thru the speaker (on phone it would be bottom) 
3. the ear piece ringer. (on phone it would be at top)

**Comment by riverar** [comment]
We made a bunch of changes to grouping in EarTrumpet 2.0. Grab it from the Microsoft Store and give it a spin (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
