### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by ghost** [File-New-Project/EarTrumpet#48]
Please add another tray icon, that will look like original windows tray volume icon

**Comment by Loilo** [comment]
That could also be a non-default option to turn on. Or if you're completely not into that at least fixing the biggest issue with the current icon would be amazing which is the lack of hinting the current volume. I'd happily abandon the default windows audio from my visible tray icon bar if that would be implemented. :)

**Comment by Jswee1** [comment]
I would love this also +1

**Comment by Droyk** [comment]
Well even I don't like the current icon is there is anyway you can change it to maybe another good sound icon.

**Comment by riverar** [comment]
We changed this internally and it'll be in the next update.

**Comment by Droyk** [comment]
okay will you able to tell us what kind of new icon did you add?

**Comment by riverar** [comment]
The exact same one as Windows.

**Comment by Jswee1** [comment]
Ok that's great and yeah what type of icon

**Comment by Droyk** [comment]
>The exact same one as Windows.

don't you think it will be hard to differentiate then?

**Comment by Droyk** [comment]
@riverar 
>The exact same one as Windows.

don't you think it will be hard to differentiate then?

**Comment by Loilo** [comment]
Maybe there should be a switch (e.g. in context menu) for switching between "original EarTrumpet icon" and "mimicking Windows icon". I'd always go for the latter (because since I use EarTrumpet, I've completely banned native sound control from my tray menu) but that would at least solve the differentiation problem.

**Comment by Droyk** [comment]
>I'd always go for the latter (because since I use EarTrumpet, I've completely banned native sound control from my tray menu)

the problem is ear trumpet right now doesn't have what windows native sound control have at the moment that's the reason I don't want to hide tray icon of the native sound control.

what I think ear trumpet should do is add 2 icons in ear trumpet first one is internal and 2nd one windows sound icon for internal they sound choose a different good white sound icon..


@riverar if you want I can make a good sound icon for you guys what do you think?

**Comment by stevek123** [comment]
I don't like the idea that it will have the same icon as the Windows 10 one

**Comment by Droyk** [comment]
>I don't like the idea that it will have the same icon as the Windows 10 one

I don't like it too but I don't think @riverar will hear to us and it's totally easy to change the icon 

What he have to do is just to change the internal icon to something more elegant and good looking sound icon and then just add the windows native icon to 2nd choice option easy isn't.

**Comment by cuprousoxide** [comment]
> We changed this internally and it'll be in the next update.

@riverar

This hasn't happened yet, has it?

**Comment by riverar** [comment]
> @cuprousoxide: This hasn't happened yet, has it?
Sadly, no. Let me talk to @GoldenTao and see what we can do to push this (and a few other things) out today. Our bad.

**Comment by riverar** [comment]
Done; 1.5 update in the store.
