### ISSUE TITLE
FR: Option to disable scroll wheel level changing, ability to Ctrl+Z to undo change.

### ISSUE THREAD

**Issue by drgruney** [File-New-Project/EarTrumpet#504]
I have a lot of devices and programs going at the same time and moving up and down the list is a tad burdensome with the scroll bar being teensy. It's also natural reflect to see a list and hit the scroll wheel. Invariably I accidentally change an audio level and don't know what the previous setting was.

I would love being able to toggle scroll to set levels off so it just scrolls through my device/application list.

Additionally being able to "Undo" the last level change could be nice in fine tuning for levels out.

**Comment by vertigo220** [comment]
I didn't even realize there was a scroll bar... If you scroll the list with the mouse over the program icons or the numeric volume level (e.g. 100), it will actually scroll. It only changes the volume when over the slider.

That said, I would like an option to change this so it _only scrolls when hovering over the numeric volume level_. I'm frequently changing the volume because, as you said, it's just habit to scroll in order to, well, scroll. I think it would be a lot better if everything left of the volume number reacted to the scroll wheel by scrolling the list, and in order to change a specific volume you'd hover over the number and scroll, or just drag the bar. I realize, of course, not everyone would like this, which is why it would need to be an option. But it's definitely frustrating the way it's currently set up.

**Comment by rgreer4** [comment]
Another vote from me.  An option of what the scroll wheel does would be excellent, one being to just scroll the list only.

I've never once tried or wanted to adjust the volume with the scroll wheel.  But I am constantly doing it by accident in my long list of audio devices.  And then either getting the mouse just right over the numbers or trying to get the scroll bar to appear to scroll the list.
