### ISSUE TITLE
Settings page is too dispersive

### ISSUE THREAD

**Issue by MarcAnt01** [File-New-Project/EarTrumpet#532]
This page in my opinion is useless.
![image](https://user-images.githubusercontent.com/43090263/88651548-0f7c5880-d0ca-11ea-9420-d05e96503973.png)
This page should be displayed directly when opening settings instead
![image](https://user-images.githubusercontent.com/43090263/88651622-27ec7300-d0ca-11ea-9fd7-a3c036698ebe.png)

**Comment by riverar** [comment]
I appreciate the issue. EarTrumpet has a rich extensibility model and a backlog of addons that I'm dragging my feet on due to a number of hurdles. Here's an example of what a more populated EarTrumpet looks like.
![image](https://user-images.githubusercontent.com/475132/88716688-4ce5e380-d0d4-11ea-802d-e6381bac3a0e.png)
