### ISSUE TITLE
Hide unnecessary app volume [Feature]

### ISSUE THREAD

**Issue by CosimoMatassini** [File-New-Project/EarTrumpet#558]
It could be useful to be able to hide an app from EarTrumpet just because I don't use it (like "System Sounds") in order not to cover too much screen and be focused on what I work with.

**Comment by Drexl** [comment]
Yes, please. Also, just generally having each audio source take up less horizontal space on the mixer would be very useful. I often have the mixer open and extended to display every audio source and it takes up a very large amount of real-estate. I'd like to see the sliders shrunk by half, and the ability to hide the system name for each device (just show the user-defined name). This would make the mixer a lot more useable for me.

**Comment by celluj34** [comment]
Adding on to this, maybe even the ability to "pin" certain apps so they show above others.

**Comment by ryantheleach** [comment]
+1 to pinning apps/devices and hiding them.

In case this is an XYproblem I figured I should explain why.

![image](https://user-images.githubusercontent.com/141554/100442743-75203600-30f8-11eb-89aa-2f6adb9ee296.png)

System Sounds and Discord are currently listed for EVERY device, no matter if they are making noise or not, or whether they are being played to a specific sound device configured inside the program.

Generally speaking, I don't ever need to adjust these on devices they are not outputting on, so they just add to the clutter.

Ideally System Sounds and Discord would only show up on the devices they are actually using. But I'm guessing this is a 3rd party bug due to keeping a sound session open for some reason or another.

**Comment by c-dot-gonz** [comment]
I have a lot of audio inputs/outputs that are needed frequently enough that I can't just disable them, but I never actually run programs to them (they're hardware inputs that I need for recording) so being able to just hide them from EarTrumpet would be amazing.

**Comment by LukasDoubleU** [comment]
I implemented this and other features over at my fork.
You can right click an app and then 'delete' or 'hide' it.
There is a button in the settings to restore all hidden apps.

If you want you can try out the pre-release:
https://github.com/LukasDoubleU/EarTrumpet/releases

![image](https://user-images.githubusercontent.com/16664756/106393144-b1705b00-63f5-11eb-84ee-817515512061.png)

**Comment by dannywrayuk** [comment]
Such a spooky coincidence! I just sat down an hour ago and began implementing this feature because I really needed it. This saves me a load of effort! Are you planning on opening a PR?

**Comment by LukasDoubleU** [comment]
Yes, I wrote a mail to the devs and am waiting for their response.
If I get their OK I will open a PR

**Comment by celluj34** [comment]
You don't need "approval" to make a PR, just do it...

**Comment by LukasDoubleU** [comment]
please read https://github.com/File-New-Project/EarTrumpet/blob/master/CONTRIBUTING.md

**Comment by davuxcom** [comment]
We kindly ask that in order to ensure your effort isn't wasted, we discuss PRs before submitting them. We still review and consider all PRs however if we collaborate early it's more likely that the technical solution will match the project goals.

https://github.com/File-New-Project/EarTrumpet/blob/master/CONTRIBUTING.md
