### ISSUE TITLE
Sources set to "Always use default device" doesn't switch output when switching between two default devices

### ISSUE THREAD

**Issue by HyperwaveGlitch** [File-New-Project/EarTrumpet#766]
## Description
I have two default devices connected. 
When I switch between them in EarTrumpet, applications doesn't switch to the new device.

## Steps to reproduce
1. Click EarTrumpet tray icon -> Right click an application -> 
   Click double arrow icon -> Select "Always use the default playback device"
1. Right click EarTrumpet -> Windows Legacy -> Playback Devices
2. Right click an active device -> Set as Default Device
3. Repeat step 2 with another active device
4. Right click EarTrumpet, click one of the devices
5. Repeat step 4 with another device

Applications that are set to always use default device are still outputting to the first selected device.
If I repeat step 1 after switching output device, the application moves to the last selected (the correct) device.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.804

**Comment by groovybluedog** [comment]
I am having the same issue and it is infuriating

**Comment by HyperwaveGlitch** [comment]
> I am having the same issue and it is infuriating

I agree. I have noticed that applications whit a dedicated "IO Device"-handler (for lack of a better term) are less prone to this bug. For example, Chrome and Discord both have options for selecting IO devices. If the selected IO in these apps is "Default", EarTrumpet can move them as intended, and reliably so. Other applications, like maybe WinRar or certain indie games which (to the best of my very limited understanding) do not have this level of communication with the IO devices/drivers, get stuck and have to be moved manually.  Maybe this can help devs find the issue.

**Comment by riverar** [comment]
What happens is somewhat non-deterministic (or _random_), I'm afraid.

Some applications, once they latch onto an audio device, ignore all changes until the app is restarted. Other applications handle the updates and follow the default audio device around. Then there's a bag of applications that do something in the middle. It's frankly a mess.

EarTrumpet is exposing the settings available in the Windows 10 [App volume and device preferences] window. (In the example below, EarTrumpet's "Always use the default playback device" maps to the Output device "Default" value.)

![image](https://user-images.githubusercontent.com/475132/116602369-7a202600-a8e0-11eb-90c2-50e1c2e67a5e.png)

I'm going to re-label this as a Windows bug and close it, as there's nothing we can really do here. You'll have the same issue using Windows 10's controls. If you see something otherwise, please feel free to re-open.
