### ISSUE TITLE
High CPU usage.. is this normal?

### ISSUE THREAD

**Issue by jvook** [File-New-Project/EarTrumpet#956]
## Description
It's constantly using 10-15% CPU is this [normal? On core i5 9600k  There is no sound even playing.
Don't know if it's related to https://github.com/File-New-Project/EarTrumpet/issues/402 because my RAM usage is only about 30MB.

## Screenshots
Here is a pastebin of error reporting https://pastebin.com/1SXjQt8F

**Comment by riverar** [comment]
Does it always happen? If so, find EarTrumpet.exe in Task Manager > Details, right-click it, Create Dump File. Then attach the dump here or email it to team@eartrumpet.app. Thanks!

**Comment by veremenko-y** [comment]
I sent my dump just now. I had to upload it to MEGA because it's like 600MB... Changing the volume in the mixer is what's triggering high CPU usage. It takes 1-3 seconds to change the slider location.
Looking at the ETW trace it seems like one thread is getting really stuck in MediaNotificationWorker, UI thread seems to be just waiting for the message, I assume it's blocking on the notification result.
![image](https://user-images.githubusercontent.com/4127660/151847759-ee01ab97-599c-4034-af71-9bd5f1186ba8.png)
![image](https://user-images.githubusercontent.com/4127660/151848118-ca87044b-cd3e-453a-b9b5-e4b58d1a5783.png)

Significant chunk of the Notification thread is in the enumeration, that could be a problem for my machine. I have motherboard audio, display port monitor audio, steinberg CL 1 audio interface, rift s vr headset, and I use bluetooth headphones. Most of those are disabled though. I don't know this API so I'm not sure if it's MS API that does something O(n^2) or maybe you call it too often.
![image](https://user-images.githubusercontent.com/4127660/151848585-1e29e473-53b4-4b07-a44f-18b37e37137c.png)

**Comment by veremenko-y** [comment]
Any news on that?

**Comment by riverar** [comment]
Nothing is jumping out at me here that indicates there's an EarTrumpet bug so closing this for now. I'll keep an eye on CPU usage issues. If you find out more, let us know!
